### ISSUE TITLE
Not match the iPhone6's size

### ISSUE THREAD

**Issue by Mil0R** [gonzalezreal/Vertigo#8]

**Comment by devios1** [comment]
I'm experiencing this as well. The sample app seems to work fine, but for some reason when I do the same thing in my app, the `TGRImageViewController` is iPhone 5 sized and docked to the top-right corner. The animation works properly, zooming to the full screen, but as soon as it finishes, jump to the incorrect size as the transition view is hidden.

**Comment by devios1** [comment]
Ah, the reason it works in the sample is because the sample is a 4-inch app upscaled. :P

**Comment by devios1** [comment]
I got around it by adding `self.view.frame = CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, [UIScreen mainScreen].bounds.size.height);` to `initWithImage:`, but I don't know where this should be properly done when presenting a full-screen view controller. I tried using Auto Layout, but it didn't make a difference.

**Comment by kevinwo** [comment]
+1'ing this with a visual aid. Thanks for the workaround, @devios1337!

![ios simulator screen shot aug 24 2015 11 03 57 am](https://cloud.githubusercontent.com/assets/371957/9432130/12178fde-4a50-11e5-885c-94aeb8b40d55.png)
