### ISSUE TITLE
`[TGRImageViewController alloc] initWithImage:` can't load the .xib file

### ISSUE THREAD

**Issue by stoneros** [gonzalezreal/Vertigo#9]
hi, sorry to bother. I’ve been studing your code from Vertigo by recreate it.  But when I’m try to using `[TGRImageViewController alloc] initWithImage]` it just don’t load the TGRImageViewController.xib file and all Outlets are nil. Can you tell me what I did wrong plz. :)

**Comment by gonzalezreal** [comment]
Can I see your code, please? :smile:

**Comment by stoneros** [comment]
hi, sorry for the delay, I just get it done. I don't know why but the same code if I choose create new Class with check the option "Also create the XIB file" then the code will work, but if I didn't and set the XIB's file's Owner's class to corresponding `ViewController` class the XIB file will not be load.
